print("Welcome to a silly madlibs program. Type your answers in and hit enter. Press enter to continue!")
next = input()
print('"Hi, I\'m a villager. Who are you?"')
low_cn = input('Name: ')
cn = low_cn.capitalize()
print('"What are your pronouns?" \n(Enter one subjective personal pronoun like He/She/They/Ze)')
pronoun = input("Pronoun: ")
cap_pronoun = pronoun.capitalize()
print(f'"Nice to meet you. Uh oh, look out, {cn}! It\'s a goblin!"')
print("What do you do?")
action = input("Present tense verb: ")
low_action = action.lower()
cap_action = action.capitalize()
print(f"You {low_action} the goblin! (press enter)")
next2 = input()
print(f'"Hey, great job, {cn}. You really did that goblin a {low_action}. Oh look it\'s the Mayor! What\'s their name?"')
mayor = input("Mayor's name: ")
cap_mayor = mayor.capitalize()
print(f'"Hi, Mayor {cap_mayor}. Have you met {cn}? {cap_pronoun} can {low_action} goblins! {cap_action} \'em good too, I saw it!" (press enter to finish your story.)')
next3 = input()
print("Everyone is happy to meet you. The End! \nThanks for playing!")
