print("Welcome to a silly madlibs program. Type your answers in and hit enter. Press enter to continue!")
next = input()
print('"Hi, I\'m a villager. Who are you?"')
cn = input('Name: ')
print('"What are your pronouns?" \n(Enter one subjective personal pronoun like He/She/They/Ze)')
pronoun = input("Pronoun: ")
print(f'"Nice to meet you. Uh oh, look out, {cn}! It\'s a goblin!"')
print("What do you do?")
action = input("Present tense verb: ")
print(f"You {action} the goblin! (press enter)")
next2 = input()
print(f'"Hey, great job, {cn}. You really did that goblin a {action}. Oh look it\'s the mayor! What\'s his name?"')
mayor = input("Mayor's name: ")
print(f'"Hi Mayor {mayor}. Have you met {cn}? {pronoun} can {action} goblins!" (press enter to finish your story.)')
next3 = input()
print("Everyone is happy to meet you. The End! \nThanks for playing!")
